version: 0.2
phases:

  install:
    runtime-versions:
      python: 3.7 
    commands: 
    


      - pip3 install yamllint
      
  pre_build:
    commands:
      
      - pip install -r requirements.txt
 
  build:
    commands:
      - ls -ltrh



      # Validate SAM template. If using SAM, keep this.
      - aws cloudformation validate-template --template-body file://EMR_CLUSTER.yml

      # EMR is not a serverless service. However, doing this allows us to mix Step, Lambda, etc. in the same template later. 
      - sam build -t $TEMPLATE
      - sam package --template-file $TEMPLATE --output-template-file emr_cluster.yml
      - pwd
      - ls -ltrh
      - git clone https://github.com/sreedharwissen/VpcRepo.git
      - cp  emr_cluster.yml ./VpcRepo/
      - git add .
      - git commit -m "commit codebuild output artifacts"
      - git push origin main
