version: 0.2
phases:

  install:
    runtime-versions:
      python: 3.7 
    commands: 
    
      - echo WebHook Event = $CODEBUILD_WEBHOOK_EVENT 
      - SOURCE_VERSION=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - pip3 install yamllint
      
  pre_build:
    commands:
      
      - pip install -r requirements.txt
 
  build:
    commands:
      - ls -ltrh

      - if [ -z "$TEMPLATE" ]; then echo "Setting default template name value..."; $TEMPLATE="EMR_CLUSTER.yml"; fi
      - echo "Template file name to be used in build -> $TEMPLATE"

      # Validate SAM template. If using SAM, keep this.
      - sam validate --template vpc.yml

      # EMR is not a serverless service. However, doing this allows us to mix Step, Lambda, etc. in the same template later. 
      - sam build -t $TEMPLATE
      - sam package --template-file $TEMPLATE --output-template-file emr_cluster.yml
      - cp emr_cluster.yml fileb://
