Resources:
  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue 'Vpc-Stack:VPC'
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-2a"
      Tags:
      - Key: stack
        Value: production
